# Generated by Django 5.2.6 on 2025-11-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineproduce", "0002_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="re_password",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="login",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="login",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterModelTable(
            name="login",
            table="login",
        ),
    ]
