# Generated by Django 5.2.6 on 2025-11-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlineproduce", "0003_login_re_password_alter_login_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="login",
            name="re_password",
        ),
        migrations.AlterField(
            model_name="login",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="login",
            name="username",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="login",
            table=None,
        ),
    ]
